name: "esc-task-tracker"
services:
  task-tracker-postgres:
    container_name: task-tracker-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - task-tracker-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - esc-net

  esc-task-tracker:
    container_name: task-tracker
    image: scobca/task-tracker:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - esc-task-tracker-data:/var/
    env_file:
      - ./.env
    networks:
      - esc-net

volumes:
  task-tracker-postgres-data:
  esc-task-tracker-data:

networks:
  esc-net:
    driver: bridge