CREATE TABLE teams
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description TEXT,
    owner_id    BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_teams PRIMARY KEY (id)
);

ALTER TABLE teams
    ADD CONSTRAINT FK_TEAMS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);