ALTER TABLE team_membership
    DROP CONSTRAINT pk_team_membership;

ALTER TABLE team_membership
    ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE team_membership
    ADD CONSTRAINT pk_team_membership PRIMARY KEY (id);

ALTER TABLE team_membership
    ADD CONSTRAINT uk_team_membership_user_team
        UNIQUE (user_id, team_id);