package org.esc.tasktracker.entities

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.FetchType
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.JoinColumn
import jakarta.persistence.ManyToOne
import jakarta.persistence.Table
import java.util.UUID

/**
 * Entity for persisting refresh tokens in the database.
 *
 * @param id Unique identifier for the token record. Auto-generated by the database.
 * @param user The user associated with this refresh token. Establishes a many-to-one
 *             relationship with the [Users] entity.
 * @param uuid Unique session identifier that binds this token to a specific client
 *             session. Must be unique across all tokens.
 * @param token The actual JWT refresh token string. Stored for validation purposes.
 *
 * @see Users
 * @see org.esc.tasktracker.services.AuthService
 * @see org.esc.tasktracker.security.JwtUtil
 *
 * @author Vladimir Fokin
 * @since 1.0
 */
@Entity
@Table(name = "jwt_tokens_storage")
data class JwtTokensStorage(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long,

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id", nullable = false)
    var user: Users,

    @Column(nullable = false, unique = true)
    var uuid: UUID,

    @Column(nullable = false)
    var token: String
)