package org.esc.tasktracker.entities

import com.fasterxml.jackson.annotation.JsonIgnore
import jakarta.persistence.*
import org.esc.tasktracker.io.TrimEntityListener
import org.springframework.data.annotation.CreatedDate
import org.springframework.data.annotation.LastModifiedDate
import org.springframework.data.jpa.domain.support.AuditingEntityListener
import java.time.Instant

/**
 * Team entity representing a group or team within the system.
 * Teams are created by a user (owner) and can be used for organizing public tasks
 *
 * @param id Unique identifier for the team. Auto-generated by the database
 *           using identity/auto-increment strategy.
 * @param name The name of the team. This is a required field and should be
 *             a concise, human-readable identifier for the team.
 * @param description An optional detailed description of the team's purpose,
 *                    goals, or rules. Stored as TEXT in the database to allow
 *                    for longer content.
 * @param owner The user who owns or created the team. This establishes a
 *                many-to-one relationship with the [Users] entity.
 * @param createdAt Timestamp when the team record was created.
 *                  Automatically set by [AuditingEntityListener].
 * @param updatedAt Timestamp when the team record was last modified.
 *                  Automatically updated by [AuditingEntityListener].
 *
 * ## Entity Listeners:
 * - **[AuditingEntityListener]**: Automatically manages [createdAt] and [updatedAt]
 *   timestamps during persist and update operations.
 * - **[TrimEntityListener]**: Automatically trims whitespace from string fields
 *   (except those marked with [@NotTrimmable]) before persist and update.
 *
 * ## Relationships:
 * - **Many-to-One with [Users]**: Multiple teams can be owned by a single user.
 *   The foreign key is stored in the `owner_id` column.
 *
 * @see Users
 * @see AuditingEntityListener
 * @see TrimEntityListener
 * @see org.esc.tasktracker.annotations.NotTrimmable
 * @see CreatedDate
 * @see LastModifiedDate
 *
 * @author Vladimir Fokin
 * @since 0.2.0
 */
@Entity
@Table(name = "teams")
@EntityListeners(AuditingEntityListener::class, TrimEntityListener::class)
data class Teams(
    @Id
    @GeneratedValue(GenerationType.IDENTITY)
    val id: Long,

    @Column(nullable = false)
    var name: String,

    @Column(nullable = true, columnDefinition = "TEXT")
    var description: String? = null,

    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "owner_id", nullable = false)
    var owner: Users,

    @CreatedDate
    var createdAt: Instant?,

    @LastModifiedDate
    var updatedAt: Instant?,

    @OneToMany(mappedBy = "team", cascade = [CascadeType.ALL], orphanRemoval = true)
    val teamMemberships: MutableSet<TeamMembership> = mutableSetOf()
) {
    val ownerId: Long
        get() = owner.id

    override fun toString(): String {
        return "Teams(id=$id, name='$name', description=$description, createdAt=$createdAt, updatedAt=$updatedAt, ownerId=$ownerId)"
    }
}
