package org.esc.tasktracker.entities

import com.fasterxml.jackson.annotation.JsonIgnore
import jakarta.persistence.CascadeType
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.EntityListeners
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.OneToMany
import jakarta.persistence.Table
import org.esc.tasktracker.annotations.NotTrimmable
import org.esc.tasktracker.io.TrimEntityListener
import org.springframework.data.annotation.CreatedDate
import org.springframework.data.annotation.LastModifiedDate
import org.springframework.data.jpa.domain.support.AuditingEntityListener
import java.time.Instant

/**
 * User entity representing the core user data in the system.
 *
 * @param id Unique identifier for the user. Auto-generated by the database
 *           using identity/auto-increment strategy.
 * @param name User's full name or display name. Required field.
 * @param email User's email address used for authentication. Must be unique
 *              across all users. Stored in lowercase typically.
 * @param password Bcrypt-hashed password. Never stored in plain text.
 *                 Marked with [@NotTrimmable] to preserve exact hash value.
 * @param createdAt Timestamp when the user account was created.
 *                  Automatically set by [AuditingEntityListener].
 * @param updatedAt Timestamp when the user account was last modified.
 *                  Automatically updated by [AuditingEntityListener].
 *
 * ## Entity Listeners:
 * - **[AuditingEntityListener]**: Automatically manages [createdAt] and [updatedAt]
 *   timestamps during persist and update operations.
 * - **[TrimEntityListener]**: Automatically trims whitespace from string fields
 *   (except those marked with [@NotTrimmable]) before persist and update.
 *
 * @see AuditingEntityListener
 * @see TrimEntityListener
 * @see NotTrimmable
 * @see CreatedDate
 * @see LastModifiedDate
 *
 * @author Vladimir Fokin
 * @since 1.0
 */
@Entity
@Table(name = "users")
@EntityListeners(AuditingEntityListener::class, TrimEntityListener::class)
data class Users(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long,

    @Column(nullable = false)
    var name: String,

    @Column(nullable = false, unique = true)
    var email: String,

    @NotTrimmable
    @Column(nullable = false)
    var password: String,

    @CreatedDate
    var createdAt: Instant?,

    @LastModifiedDate
    var updatedAt: Instant?,

    @JsonIgnore
    @OneToMany(mappedBy = "ownerId", cascade = [CascadeType.ALL], orphanRemoval = true)
    val events: MutableList<Teams>? = mutableListOf(),
)
