name: Create deployment notification
on:
  repository_dispatch:
    types: [ successful-deployment ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send TG message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            ${{ github.event.client_payload.actor }} deployed version v${{ github.event.client_payload.version }} 
            
            🔗 ${{ github.server_url }}/${{ github.event.client_payload.repo }}
